version: '3'
services:
  mongo-primary:
    image: mongo:latest
    container_name: mongo-primary
    ports:
      - 27017:27017
    volumes:
      - mongodb-primary-data:/data/db
      - ./mongo-primary:/docker-entrypoint-initdb.d
    command: --replSet testReplica --bind_ip 0.0.0.0
    restart: always
    depends_on:
      - mongo-secondary

  mongo-secondary:
    image: mongo:latest
    container_name: mongo-secondary
    ports:
      - 27018:27017
    volumes:
      - mongodb-secondary-data:/data/db
    restart: always
    command: --replSet testReplica --bind_ip 0.0.0.0

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-primary
    depends_on:
      - mongo-primary

  mongo-app:
    image: golang:1.13.5-alpine
    container_name: mongo-app
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      GOFLAGS: '-mod=vendor'
    command: go run main.go


volumes:
  mongodb-primary-data:
  mongodb-secondary-data: